name: Deploy Feature Flags
on:
  workflow_dispatch:
  push:

jobs:
  validate-feature-flags:
    runs-on: ubuntu-latest
    env:
      APP_CONFIGURATION_FILE: .config/feature-flags.json
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate App Config feature flags
        uses: azure/app-configuration-deploy-feature-flags@v1-beta
        with:
          path: ${{ env.APP_CONFIGURATION_FILE }}
          operation: validate
